spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: vijayjason86@gmail.com
    password: qyeakzcdetivrxcz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#twilio:
#  account-sid: 'ACdee36a51856c99213fee9da477584893'
#  auth-token: '157fb52af61721434fe48bde72bbdd68'
#  phone-number: '+17156391239'
